"""
Feature Pyramid Network (FPN)
==============================
Builds a top-down multi-scale feature hierarchy from backbone outputs.

Design:
  - Lateral 1×1 convs project each backbone level to out_channels
  - Top-down pathway: upsample coarser + add to finer (element-wise)
  - Output 3×3 conv on each merged level removes aliasing
  - Optional extra levels (P6, P7) via stride-2 conv on P5 (for large objects)

Input  (from Swin-T, out_indices=[1,2,3]):
  [(B, 192, H/8,  W/8 ),
   (B, 384, H/16, W/16),
   (B, 768, H/32, W/32)]

Output (out_channels=256, num_outs=4):
  [P2: (B, 256, H/8,  W/8 ),   ← finest  → depth/seg heads
   P3: (B, 256, H/16, W/16),
   P4: (B, 256, H/32, W/32),   ← coarsest backbone level
   P5: (B, 256, H/64, W/64)]   ← extra level via stride-2 conv

Reference: Lin et al. "Feature Pyramid Networks for Object Detection"
           CVPR 2017. https://arxiv.org/abs/1612.03144
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import List


class FPN(nn.Module):
    """
    Feature Pyramid Network.

    Args:
        in_channels  : list of input channel counts per backbone level,
                       ordered fine→coarse (e.g. [192, 384, 768] for Swin-T).
        out_channels : uniform output channel count for all pyramid levels.
        num_outs     : total pyramid levels to produce. If > len(in_channels),
                       extra levels are generated by strided conv on the
                       coarsest feature (add_extra_convs must be set).
        start_level  : index into in_channels to start the FPN from.
                       Useful to skip the finest backbone level if too large.
        add_extra_convs : how to generate extra levels beyond backbone:
                       'on_input'  — stride-2 conv on the last backbone feature
                       'on_output' — stride-2 conv on the last FPN output (P_last)
                       False / None — no extra levels (num_outs <= len(in_channels))
        relu_before_extra : apply ReLU before each extra strided conv.
    """

    def __init__(
        self,
        in_channels:       List[int],
        out_channels:      int,
        num_outs:          int,
        start_level:       int  = 0,
        add_extra_convs:   str  = "on_output",   # 'on_input' | 'on_output' | False
        relu_before_extra: bool = False,
    ):
        super().__init__()
        assert isinstance(in_channels, (list, tuple))
        self.in_channels      = in_channels
        self.out_channels     = out_channels
        self.num_ins          = len(in_channels)
        self.num_outs         = num_outs
        self.start_level      = start_level
        self.add_extra_convs  = add_extra_convs
        self.relu_before_extra = relu_before_extra

        # Backbone levels actually used (start_level : end_level)
        self.backbone_end_level = self.num_ins   # use all levels by default

        used_levels = self.num_ins - start_level  # how many backbone levels we use

        # ── Lateral 1×1 projections: backbone_ch → out_channels ──────────
        self.lateral_convs = nn.ModuleList()
        for i in range(start_level, self.backbone_end_level):
            self.lateral_convs.append(
                nn.Sequential(
                    nn.Conv2d(in_channels[i], out_channels, 1, bias=False),
                    nn.BatchNorm2d(out_channels),
                )
            )

        # ── Output 3×3 convs (post top-down merge) ───────────────────────
        self.fpn_convs = nn.ModuleList()
        for _ in range(used_levels):
            self.fpn_convs.append(
                nn.Sequential(
                    nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False),
                    nn.BatchNorm2d(out_channels),
                    nn.ReLU(inplace=True),
                )
            )

        # ── Extra levels beyond backbone (e.g. P6 from P5) ───────────────
        extra_levels = num_outs - used_levels
        self.extra_convs = nn.ModuleList()
        if add_extra_convs and extra_levels > 0:
            for i in range(extra_levels):
                # Input to first extra conv depends on add_extra_convs mode
                in_ch = out_channels   # always out_channels after the first level
                self.extra_convs.append(
                    nn.Sequential(
                        nn.Conv2d(in_ch, out_channels, 3, stride=2, padding=1, bias=False),
                        nn.BatchNorm2d(out_channels),
                        nn.ReLU(inplace=True),
                    )
                )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, inputs: List[torch.Tensor]) -> List[torch.Tensor]:
        """
        Args:
            inputs : list of backbone feature maps, fine→coarse.
                     Each (B, C_i, H_i, W_i).

        Returns:
            List of FPN feature maps, fine→coarse, each (B, out_channels, H_i, W_i).
            Length == num_outs.
        """
        assert len(inputs) == self.num_ins, (
            f"FPN expected {self.num_ins} inputs, got {len(inputs)}"
        )

        # ── Lateral projections ───────────────────────────────────────────
        # laterals[0] = finest used level, laterals[-1] = coarsest
        laterals = [
            conv(inputs[i + self.start_level])
            for i, conv in enumerate(self.lateral_convs)
        ]

        # ── Top-down pathway: coarse → fine ──────────────────────────────
        # Start from the coarsest and add upsampled version to next finer level
        num_used = len(laterals)
        for i in range(num_used - 1, 0, -1):
            coarse = laterals[i]
            fine   = laterals[i - 1]
            # Upsample coarse to match fine's spatial size
            upsampled = F.interpolate(
                coarse, size=fine.shape[2:], mode="nearest"
            )
            laterals[i - 1] = fine + upsampled

        # ── Output 3×3 convs ─────────────────────────────────────────────
        outs = [
            self.fpn_convs[i](laterals[i])
            for i in range(num_used)
        ]

        # ── Extra levels (P6, P7, …) ─────────────────────────────────────
        if self.add_extra_convs and self.extra_convs:
            if self.add_extra_convs == "on_input":
                # Stride-2 conv on the last *backbone* feature (before FPN)
                extra_src = inputs[self.backbone_end_level - 1]
            else:  # "on_output"
                # Stride-2 conv on the last *FPN output* (P_last)
                extra_src = outs[-1]

            outs.append(self.extra_convs[0](extra_src))
            for extra_conv in self.extra_convs[1:]:
                outs.append(extra_conv(outs[-1]))

        assert len(outs) == self.num_outs, (
            f"FPN produced {len(outs)} outputs, expected {self.num_outs}"
        )
        return outs


def build_fpn(cfg: dict) -> FPN:
    """Instantiate FPN from config dict (neck section of YAML)."""
    return FPN(
        in_channels=cfg["in_channels"],
        out_channels=cfg["out_channels"],
        num_outs=cfg.get("num_outs", len(cfg["in_channels"])),
        start_level=cfg.get("start_level", 0),
        add_extra_convs=cfg.get("add_extra_convs", "on_output"),
        relu_before_extra=cfg.get("relu_before_extra", False),
    )